# Generated by Django 4.1.7 on 2023-05-17 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_remove_usercomic_series_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserReadIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.issue')),
            ],
        ),
        migrations.RemoveField(
            model_name='usercomic',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='usercomic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='read_comics',
        ),
        migrations.DeleteModel(
            name='Comic',
        ),
        migrations.DeleteModel(
            name='UserComic',
        ),
        migrations.AddField(
            model_name='userreadissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.series'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_issues',
            field=models.ManyToManyField(blank=True, through='comics.UserReadIssue', to='comics.issue'),
        ),
    ]
